version: '3.9'

services:
  postgres:
    container_name: leads_db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_leads

volumes:
  postgres_data:

networks:
  postgres_leads: